RideCompanion/Controllers/CompanionController.cs
using Companion.App.Commands;
using Companion.App.Queries;
using MediatR;
using Microsoft.AspNetCore.Mvc;
using RideCompanion.ViewModels;

namespace RideCompanion.Controllers;

/// <summary>
/// 
/// </summary>
public class CompanionController : Controller
{
    private readonly IMediator _mediator;

    public CompanionController(IMediator mediator)
    {
        _mediator = mediator;
    }
    
    public async Task<IActionResult> Index()
    {
        var data = await _mediator.Send(new GetCompanionsQuery());
        
        if (data.Any())
        {
            ViewData["data"] = data.ToList();
        }
        
        return View(new CompanionViewModel());
    }
    
    /// <summary>
    /// 
    /// </summary>
    /// <param name="id"></param>
    /// <returns></returns>
    public async Task<IActionResult> GetCompanionById(Guid id)
    {
        var data = await _mediator.Send(new GetCompanionByIdQuery(id));
        return Json(data);
    }

    /// <summary>
    /// 
    /// </summary>
    /// <param name="viewModel"></param>
    /// <returns></returns>
    public async Task<IActionResult> CreateCompanion(CompanionViewModel viewModel)
    {
        await _mediator.Send(new CreateCompanionCommand(viewModel.CompanionDto));
        return RedirectToAction("Index");
    }

    /// <summary>
    /// 
    /// </summary>
    /// <param name="viewModel"></param>
    /// <returns></returns>
    public async Task<IActionResult> UpdateCompanion(CompanionViewModel viewModel)
    {
        await _mediator.Send(new UpdateCompanionCommand(viewModel.CompanionDto));
        return RedirectToAction("Index");
    }

    /// <summary>
    /// 
    /// </summary>
    /// <param name="id"></param>
    /// <returns></returns>
    public async Task<IActionResult> DeleteCompanion(Guid id)
    {
        await _mediator.Send(new DeleteCompanionCommand(id));
        return RedirectToAction("Index");
    }
}

RideCompanion/Controllers/DriverController.cs
using Driver.App.Commands;
using Driver.App.Queries;
using MediatR;
using Microsoft.AspNetCore.Mvc;
using RideCompanion.ViewModels;

namespace RideCompanion.Controllers;

/// <summary>
/// Driver
/// </summary>
public class DriverController : Controller
{
    private readonly IMediator _mediator;

    public DriverController(IMediator mediator)
    {
        _mediator = mediator;
    }

    /// <summary>
    /// Index
    /// </summary>
    /// <returns> View </returns>
    public async Task<IActionResult> Index()
    {
        var data = await _mediator.Send(new GetDriversQuery());
        
        if (data.Any())
        {
            ViewData["data"] = data.ToList();
        }
        
        return View(new DriverViewModel());
    }

    /// <summary>
    /// Get driver by Id
    /// </summary>
    /// <param name="id"> Driver Id </param>
    /// <returns> Driver entity </returns>
    public async Task<IActionResult> GetDriverById(Guid id)
    {
        var data = await _mediator.Send(new GetDriverByIdQuery
        {
            Id = id
        });
        
        if (data != null)
        {
            ViewData["driver"] = data;
        }

        return Json(data);
    }

    /// <summary>
    /// Create
    /// </summary>
    /// <param name="viewModel"> Driver view model </param>
    /// <returns> Redirect to index page </returns>
    public async Task<IActionResult> CreateDriver(DriverViewModel viewModel)
    {
        await _mediator.Send(new CreateDriverCommand
        {
            FullName = viewModel.DriverDto.FullName,
            BirthDate = viewModel.DriverDto.BirthDate
        });

        return RedirectToAction("Index");
    }

    /// <summary>
    /// Update
    /// </summary>
    /// <param name="viewModel"> Driver view model </param>
    /// <returns> Redirect to index page </returns>
    public async Task<IActionResult> UpdateDriver(DriverViewModel viewModel)
    {
        await _mediator.Send(new UpdateDriverCommand
        {
            DriverId = viewModel.DriverDto.Id,
            DriverDto = viewModel.DriverDto
        });
        
        return RedirectToAction("Index");
    }

    /// <summary>
    /// Delete
    /// </summary>
    /// <param name="id"> Driver Id </param>
    /// <returns> Redirect to index page </returns>
    public async Task<IActionResult> DeleteDriver(Guid id)
    {
        await _mediator.Send(new DeleteDriverCommand
        {
            DriverId = id
        });
        
        return RedirectToAction("Index");
    }
    
    // -------------------------------------------
    // Car
    // -------------------------------------------
    
    /// <summary>
    /// Cars
    /// </summary>
    /// <param name="driverId"> Driver id </param>
    /// <returns> View </returns>
    public async Task<IActionResult> Cars(Guid driverId)
    {
        var data = await _mediator.Send(new GetCarsByDriverIdQuery
        {
            DriverId = driverId
        });

        if (data.Any())
        {
            ViewData["data"] = data.ToList();
        }
        
        return View();
    }
    

    /// <summary>
    /// Get car by Id
    /// </summary>
    /// <param name="id"> Car Id </param>
    /// <returns> Car entity </returns>
    public async Task<IActionResult> GetCarById(Guid id)
    {
        var data = await _mediator.Send(new GetCarByIdQuery
        {
            Id = id
        });
        
        if (data != null)
        {
            ViewData["car"] = data;
        }

        return Json(data);
    }

    /// <summary>
    /// Create
    /// </summary>
    /// <param name="viewModel"> Driver view model </param>
    /// <returns> Redirect to index page </returns>
    public async Task<IActionResult> CreateCar(DriverViewModel viewModel)
    {
        await _mediator.Send(new CreateCarCommand
        {
            Number = viewModel.CarDto.Number,
            Color = viewModel.CarDto.Color,
            Model = viewModel.CarDto.Model
        });

        return RedirectToAction("Cars");
    }

    /// <summary>
    /// Update
    /// </summary>
    /// <param name="viewModel"> Driver view model </param>
    /// <returns> Redirect to index page </returns>
    public async Task<IActionResult> UpdateCar(DriverViewModel viewModel)
    {
        await _mediator.Send(new UpdateCarCommand
        {
            CarId = viewModel.CarDto.Id,
            CarDto = viewModel.CarDto
        });
        
        return RedirectToAction("Cars");
    }

    /// <summary>
    /// Delete
    /// </summary>
    /// <param name="id"> Car Id </param>
    /// <returns> Redirect to index page </returns>
    public async Task<IActionResult> DeleteCar(Guid id)
    {
        var data = await _mediator.Send(new DeleteCarCommand
        {
            CarId = id
        });
        
        return RedirectToAction("Cars");
    }
}

RideCompanion/Controllers/TripController.cs
using MediatR;
using Microsoft.AspNetCore.Mvc;
using RideCompanion.ViewModels;
using Trip.App.Commands;
using Trip.App.Queries;

namespace RideCompanion.Controllers;

/// <summary>
/// 
/// </summary>
public class TripController : Controller
{
    private readonly IMediator _mediator;

    public TripController(IMediator mediator)
    {
        _mediator = mediator;
    }
    
    /// <summary>
    /// Index
    /// </summary>
    /// <returns> View </returns>
    public async Task<IActionResult> Index()
    {
        var data = await _mediator.Send(new GetTripsQuery());
        
        if (data.Any())
        {
            ViewData["data"] = data.ToList();
        }
        
        return View(new TripViewModel());
    }

    /// <summary>
    /// 
    /// </summary>
    /// <param name="id"></param>
    /// <returns></returns>
    public async Task<IActionResult> GetTripById(Guid id)
    {
        var data = await _mediator.Send(new GetTripByIdQuery(id));
        return Json(data);
    }

    /// <summary>
    /// 
    /// </summary>
    /// <param name="viewModel"></param>
    /// <returns></returns>
    public async Task<IActionResult> CreateTrip(TripViewModel viewModel)
    {
        await _mediator.Send(new CreateTripCommand(viewModel.TripDto));
        return RedirectToAction("Index");
    }

    /// <summary>
    /// 
    /// </summary>
    /// <param name="viewModel"></param>
    /// <returns></returns>
    public async Task<IActionResult> UpdateTrip(TripViewModel viewModel)
    {
        await _mediator.Send(new UpdateTripCommand(viewModel.TripDto));
        return RedirectToAction("Index");
    }

    /// <summary>
    /// 
    /// </summary>
    /// <param name="id"></param>
    /// <returns></returns>
    public async Task<IActionResult> DeleteTrip(Guid id)
    {
        await _mediator.Send(new DeleteTripCommand(id));
        return RedirectToAction("Index");
    }
}

RideCompanion/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Mvc.TagHelpers
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - RideCompanion</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/RideCompanion.styles.css" asp-append-version="true"/>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container-fluid">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">RideCompanion</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Trip" asp-action="Index">Trip</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Driver" asp-action="Index">Driver</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Companion" asp-action="Index">Companion</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                    </li>
                </ul>
                <partial name="_LoginPartial"/>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2022 - RideCompanion - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", false)
</body>
</html>